# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c0c26b034fa53b9ee4955d1fda6f99645642e5793a298dd6a314fde8f68301a92c73bd4d42a8a028737cc2fb0b55d90391a90daa26f60fe09d9ebf54afe0f0d6

test:
  secret_key_base: 34777124d8749a2e3ad1584b06a141692b11c15c4c0de7c77543974b29c8fa5d9be5e70c2e835e4095220dab5faa559af9eac232c94bf80be71aab4c3e5eb179

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
